import { checkbox, integer, relationship, text, timestamp } from '@keystone-6/core/fields'

module.exports = {
    fields: {
        schoolName: text(),
        schoolNameAbbr: text(),
        director: relationship({ ref: 'Teacher', many: false }),
        address: text(),
        website: text(),
        email: text(),
        phone: text(),
        fax: text(),
        schedule: text(),
        founder: text(),
        founderAddress: text(),
        founderWebSite: text(),
        founderEmail: text(),
        founderPhone: text(),
        hasPreSchoolEducationLevel: checkbox(),
        hasPrimarySchoolEducationLevel: checkbox(),
        hasSecondarySchoolEducationLevel: checkbox(),
        OGRN: integer(),
        INN: integer(),
        INNStartDate: timestamp(),
        KPP: integer(),
        OKOPF: text(),
        OKFS: text(),
        licenseNumber: integer(),
        licenseStartDate: timestamp(),
        isLicensePermanent: checkbox(),
        licenseEndDate: timestamp(),
        accreditationRegNumber: text(),
        accreditationSerialNumber: text(),
        accreditationStartDate: timestamp(),
        accreditationEndDate: timestamp(),
        numOfFirstGrades: integer(),
        numOfSecondGrades: integer(),
        numOfThirdGrades: integer(),
        numOfFourthGrades: integer(),
        numOfFifthrades: integer(),
        numOfSixthGrades: integer(),
        numOfSeventhGrades: integer(),
        numOfEighthGrades: integer(),
        numOfNenethGrades: integer(),
        numOfTenthGrades: integer(),
        numOfEleventhGrades: integer(),
        numOfElementarySchoolPupils: integer(),
        numOfMiddleSchoolPupils: integer(),
        numOfHighSchoolPupils: integer(),
        gradeOneVacantPlaces: integer(),
        gradeFiveVacantPlaces: integer(),
        vacantPlacesUpdateDate: timestamp()
    }
}
